### ISSUE TITLE
Update README.md with Hacktoberfest banner and brief introduction 

### ISSUE THREAD

**Issue by pantbibek21** [kaal-coder/HacktoberFest#14]
Hello @kaal-coder , first of all, thanks for this initiative with Hactoberfest-For-All open-source repo which encourages beginners to contribute to open source. I would like to add a hacktoberfest banner along with a brief introduction to Hacktoberfest to better provide the context of hacktoberfest and also create a better user experience to contribute. I could also add a few emojis to engage the visitors of this repo. 
I would love to update README.md if you like the idea : )
Thanks

**Comment by kaal-coder** [comment]
@pantbibek21 Thanks for contributing
But it seems like my repository has been excluded from hacktoberfest.
The reason seems unknown.
So you can just do one thing, hop on to my other repository and do the same procedure.
I'll accept ASAP I get the request.

https://github.com/kaal-coder/hacktoberfest
