### ISSUE TITLE
Electricity Bill Calculator

### ISSUE THREAD

**Issue by ilhamansari** [kaal-coder/HacktoberFest#9]
A simple electricity bill calculator made using C programming language. It calculates the bill when the user enters the number of units of electricity consumed. 

https://user-images.githubusercontent.com/102286043/196891561-0e6dccdb-a370-42f0-a0a4-1c7ab5b090f8.mp4

**Comment by ilhamansari** [comment]
Please assign me this issue under hacktoberfest @kaal-coder

**Comment by kaal-coder** [comment]
Sure will do after verification.
Till then you can star the repository

**Comment by ilhamansari** [comment]
Sure @kaal-coder . Done, already.

**Comment by kaal-coder** [comment]
@ilhamansari Thanks for contributing
But it seems like my repository has been excluded from hacktoberfest.
The reason seems unknown.
So you can just do one thing, hop on to my other repository and do the same procedure.
I'll accept ASAP I get the request.

https://github.com/kaal-coder/hacktoberfest
